<?php 
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_client-fields',
		'title' => 'Client Fields',
		'fields' => array (
			array (
				'key' => 'field_57191f0a69ed9',
				'label' => 'Contact Name',
				'name' => 'contact',
				'type' => 'text',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'null',
							'operator' => '==',
							'value' => '',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57191f1969eda',
				'label' => 'Contact E-Mail',
				'name' => 'contact_e-mail',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57191f2c69edb',
				'label' => 'Billing Address',
				'name' => 'billing_address',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_57191f4569edc',
				'label' => 'Phone Number',
				'name' => 'phone_number',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'client',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_invoice-fields',
		'title' => 'Invoice Fields',
		'fields' => array (
			array (
				'key' => 'field_57191d1ae0335',
				'label' => 'Client',
				'name' => 'client',
				'type' => 'post_object',
				'required' => 1,
				'post_type' => array (
					0 => 'client',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_57191d30e0336',
				'label' => 'Invoice Number',
				'name' => 'invoice_number',
				'type' => 'number',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_57191dd3a042d',
				'label' => 'Date of Issue',
				'name' => 'date_of_issue',
				'type' => 'date_picker',
				'required' => 1,
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 0,
			),
			array (
				'key' => 'field_57191deaa042e',
				'label' => 'Due Date',
				'name' => 'due_date',
				'type' => 'date_picker',
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_57191e02a042f',
				'label' => 'PO Number',
				'name' => 'po_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_572768057c108',
				'label' => 'Status',
				'name' => 'status',
				'type' => 'select',
				'required' => 1,
				'choices' => array (
					'Unsent' => 'Unsent',
					'Sent' => 'Sent',
					'Paid' => 'Paid',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_57191e5ea0432',
				'label' => 'Line Item',
				'name' => 'line_item',
				'type' => 'repeater',
				'required' => 1,
				'sub_fields' => array (
					array (
						'key' => 'field_57191e69a0433',
						'label' => 'Task',
						'name' => 'task',
						'type' => 'text',
						'required' => 1,
						'column_width' => 60,
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_57191e75a0434',
						'label' => 'Rate',
						'name' => 'rate',
						'type' => 'number',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_57191e7da0435',
						'label' => 'Hours',
						'name' => 'hours',
						'type' => 'number',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
					array (
						'key' => 'field_5719274776a30',
						'label' => 'Total',
						'name' => 'total',
						'type' => 'number',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
						'readonly' => 1,
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_5719275f76a32',
				'label' => 'Invoice Total',
				'name' => 'invoice_total',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
				'readonly' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'invoice',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 1,
	));
}
